#
# This web application predicts the amount timber that can be harvested from 
# a black cherry tree with the given girth, or diameter at the height of 4'6", 
# and the height of the tree. 

# https://mhthom2.shinyapps.io/FinalProject/

library(shiny)
library(plotly)

set.seed(0)

# Black Cherry tree data
data(trees)

# UI for gathering user girth and height values, displaying results of prediction 
fluidPage(

    # Application title
    titlePanel("Predict Volume of Timber in a Black Cherry Tree"),

    # Sidebar with a slider for user inputs
    sidebarLayout(
        sidebarPanel(
                
            # Display directions 
            h4('Directions:'),
            h5(paste('This web application predicts the amount timber in cubic feet that can be', 
                     'harvested from a black cherry tree with the given girth, or', 
                     'diameter at the height of 4 ft 6 inches, and the height of the tree.')),
            h5(paste('To make a prediction, adjust the girth and/or height,',
                     'and the prediction will be updated below.')),
            h5(paste('The plot displays the data in blue,',
                     'the regression plane generated by the linear model used to',
                     'to make the predictions, and the point in red represents', 
                     'the data point with the volume prediction and the inputted girth and height values.')),

            # Numeric input of tree girth
            numericInput("girth",
                        "Girth of the Tree (inches):",
                        min = min(trees$Girth),
                        max = max(trees$Girth),
                        value = mean(trees$Girth)), 
            # Numeric input of tree height 
            numericInput("height",
                         "Height of the Tree (ft):",
                         min = min(trees$Height),
                         max = max(trees$Height),
                         value = mean(trees$Height)), 
            ),

        # Show a plot of the data, the regression plane, and the prediction
        mainPanel(
                h4('Predicted Volume of Timber (cubic ft):'),
                textOutput('prediction'),
                h4('Plot of data, prediction, and model regression plane:'),
                plotlyOutput("plot3D")
        )
    )
)
